export const vocabularies = [
  { word: "Apple" },
  { word: "Book" },
  { word: "Cat" },
  { word: "Dog" },
  { word: "Elephant" },
  { word: "Flower" },
  { word: "Grapes" },
  { word: "House" },
  { word: "Island" },
  { word: "Juice" },
  { word: "Kite" },
  { word: "Lion" },
  { word: "Mountain" },
  { word: "Night" },
  { word: "Ocean" },
  { word: "Pencil" },
  { word: "Queen" },
  { word: "River" },
  { word: "Sun" },
  { word: "Tree" },
];
